### ISSUE TITLE
Blob is not defined

### ISSUE THREAD

**Issue by dennisjuanito** [Errorname/google-docs-mustaches#3]
# I got an error when running the sample code

`[AsyncFunction: interpolate]
(node:22336) UnhandledPromiseRejectionWarning: ReferenceError: Blob is not defined
    at /Users/dju/Documents/inside document/danacita/PdfJS/thislibrarytest/node_modules/google-docs-mustaches/lib/apis/fetch.js:15:35
    at Object.copy (/Users/dju/Documents/inside document/danacita/PdfJS/thislibrarytest/node_modules/google-docs-mustaches/lib/apis/apis.js:14:36)
    at Mustaches.copyFile (/Users/dju/Documents/inside document/danacita/PdfJS/thislibrarytest/node_modules/google-docs-mustaches/lib/Mustaches.js:24:14)
    at Mustaches.interpolate (/Users/dju/Documents/inside document/danacita/PdfJS/thislibrarytest/node_modules/google-docs-mustaches/lib/Mustaches.js:12:39)
    at Object.interpolate (/Users/dju/Documents/inside document/danacita/PdfJS/thislibrarytest/index.js:18:11)
    at Module._compile (module.js:652:30)
    at Module._compile (/Users/dju/Documents/inside document/danacita/PdfJS/thislibrarytest/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/dju/Documents/inside document/danacita/PdfJS/thislibrarytest/node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:565:32)
(node:22336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by Errorname** [comment]
Hey there! Thank you for bringing up this issue. This is an issue with `Blob` being a browser-only api and not supported by NodeJS. I'll try to fix this issue in the coming days.

**Comment by dennisjuanito** [comment]
That's what I am thinking as well. Cool. I am looking forward to that.

**Comment by Errorname** [comment]
Hi @dennisjuanito, I published a new version of google-docs-mustaches (v0.2.0) which ensures compatibility with NodeJS 6+.

This should solve your issue :)
